[package]
name = "cw721-marketplace-utils"
version = "0.1.5"
edition = "2021"

[dependencies]
cosmwasm-std.workspace = true
schemars.workspace = true
serde.workspace = true
thiserror.workspace = true
cw20.workspace = true